### ISSUE TITLE
Initial Pressure Sensor Schematic Review

### ISSUE THREAD

**Issue by rcastle1** [badgerloop-software/hardware#1]
Initial comments on Pressure Sensor Schematic by @btobin86

@btobin86 can you make a branch and push your schematic to a branch? 
In Git Bash, once you are in the "master" directory
`git checkout -b bt_pressure_sensor`
Then add/commit your changes
`git status` to see what's changed
`git commit <file_name>`
`git push --set-upstream origin bt_pressure_sensor'
 

![Capture (5)](https://user-images.githubusercontent.com/25836359/63640022-0c722000-c650-11e9-96d4-eae2979a34d7.PNG)

1. 100KHz is probably fine, but will determined by microcontroller selection
2. In the pod III and IV designs, we intended the resistors selection to be configurable between the current output and voltage output type sensors, so that you only had to populate a 0 Ohm resistor to switch between the two, and didn't have to worry about the scaling. This worked, but the recalculation of the resistor values would allow us to utilize the full range of each sensor. Some pressure sensors are 0.5-4.5V output (0.5V at 0PSI, 4.5V at their full scale PSI, and more or less linear in between), others have a 4-20mA output (4mA at 0PSI, 20mA at full scale)

For the voltage output type, we use a voltage divider. A voltage divider works by turning a larger voltage into a smaller one, following the equation Vout=Vin*(R2/(R1+R2)) where R1 is the top resistor, and R2 is the bottom resistor. See https://learn.sparkfun.com/tutorials/voltage-dividers/all

For the current output sensor, it's difficult to measure current directly, so we will measure it indirectly, using a shunt resistor, which is a resistor connected to the output of the sensor and ground (the configuration resistors/headers are used to bypass the top resistor used in the voltage divider. The pressure sensor is a constant current source (assuming constant pressure), meaning it will always output the same current (with power limitations). So we use V=IR, where V is the output voltage we want to measure, I is the output current, and R is the resistance. 

3. Yeah, the PTC fuses are low impedance, until a large amount of current flows, in which they increase their resistance and protect the device, cuz ADCs are like $15 and PTC fuses are like $0.15. 

And then a few other things:
1. make sure your net names match. I see +5V and POS5V, altium will see these as two separate nets and not make a connection. 
2. Differentiate I2C SDA and SCK net names
3. The 7.15K resistors connecting ADC I2C lines should be 0Ohm
4. Add pull up resistors to the i2c bus
5. Rename ADC reference designator U? in component library. R=Resitor, C=Capacitor, U=integrated circuit, D=Diode, L=inductor, Q=FET/BJT, usually
6. Add a low pass filter between DUCER_OUT_X and the input to the fuse. This is a resistor between DUCER_OUT_X and the fuse, and a capacitor (which you could re-purpose) between the resistor/fuse connection node and GND. fc=1/(2*pi*R*C), where fc is your cutoff frequency, R is your resistance in Ohms, and C is your capacitance in F. 50Hz is a good place to start. It's also a good idea to include the calc in the schematic directly so you or the person looking at it doesn't have to do the math each time.
7. Add pull up and pull down 0Ohm resistors on the address lines. We'll need to have 2 of these ADCs on a single board, and need to differentiate between the two. Make sure to DNP (do not populate) the resistors connecting to 5V. right now, there's a direct short between 5V and GND
8. Floating capacitor underneath the title block
9. Also, let's get start annotating schematics when we post them, even if it's just for review. This is most easily done by `Tools>Annotate>Annotate Schematics Quietly` (TAU keyboard shortcut). This will replace all of the ? with numbers. We'll have to reset later, but it will make it easier to review.
10. I like to have the bypass resistors tied directly on the same net as Vdd, but that's just convention. 

Overall, a good start! Don't worry about the quantity of comments. There are a ton of details and what not.

**Comment by brtobin** [comment]
Just fixed some of the easy stuff right away, will go back and look further later tonight at the shunt resistor, etc.

**Comment by rcastle1** [comment]
![image](https://user-images.githubusercontent.com/25836359/63825874-4cb3f580-c911-11e9-9cea-d37fa86fe51b.png)
Can you re-arrange those components to match a low pass filter? I did the connection for ducer 7. Feel free to re-arrange, I just did that quick to show what the connection should look like

**Comment by rcastle1** [comment]
I also tend to have larger resistance values and smaller capacitance values. the tolerance range for capacitors is usually really high, unfortunately. Also, the capacitors selected is only rated to 4V, which is technically higher than what this net will see, it's still not great. There's a thing called DC biasing, where your effective capacitance can be severely limited when you apply a DC voltage across a capacitor. 

Derating the cap 50%, which is definitely possible (effective capacitance of 11uF instead of 22uF), would double Fc. For this application, it probably doesn't matter, but if you are designing for really tight tolerance, something to keep in mind. Thinking about it some more, keeping the cutoff frequency is below 60Hz is preferable, as 60Hz noise from our AC power supplies is super common. 

You can also use a calculator like this http://sim.okawa-denshi.jp/en/CRtool.php, mostly interested in step response being quick and non-oscillation

**Comment by rcastle1** [comment]
If you go to Panels > Manufacturer Part Search and search for the ADC, you can actually link all of the parameters directly to the model. (Right click, add supplier links and parameters while you are in the library editor). It's also handy to make footprints at the same time you make new schematic symbols. 

Also, with the schematic symbol, this is more style, but feel free to give yourself a bit of room between pins. I'd put VDD all the way a the top and VSS at the bottom, with some space between the other pins. This minimizes the number of net crossings. Another style thing is to put inputs on the left side, outputs on the right side. This helps when you read a schematic. Neither thing affects functionality, but good style makes things easier down the road.

**Comment by rcastle1** [comment]
Also, these are differential inputs. that's fine, but we're paying more even though we only need single-ended inputs. Have you looked at any other ADC options?

**Comment by rcastle1** [comment]
* TVS Diode: Is this the unidirectional diode? if so, symbol is upside down. Bidirectional is probably better and offers more protection. 
* Power: Want to make sure we DNP R2, R3, R4, R5... or at least one of the pair so that we don't short the 5 and 24V buses together when we first power it on. (Go to the part, add a DNP parameter, mark it as DNP, and make it visible)
* Thermistor: Avoid using components from the misc. devices and connectors library. Those are ok if you're just doing a schematic, but it becomes an issue for footprints and try to automatically create a bill of materials with components and what not. 
* Thermistor: We'd want to have the option use an external thermistor rather than 2 board mount ones. How do you think we could break this out to a harness? 
![image](https://user-images.githubusercontent.com/25836359/64468776-28fd6600-d0ee-11e9-9d48-13541436805a.png)
* A couple of random components floating around (R26). Each of these will show up as a real, physical component and a waste of space in the layout
* Try to keep text straight and horizontal, especially when you have room. Reading vertical text is ok if you're really tight, but not necessary most of the time. 
![image](https://user-images.githubusercontent.com/25836359/64468739-c60bcf00-d0ed-11e9-9577-81af0f4915d9.png)
* Similar comment for the low pass filter. 
* I also prefer to move the reference designator and component value closer to the resistor to more tightly pack lines and avoid overlap. difficult to read R36, R37, etc. here. 
![image](https://user-images.githubusercontent.com/25836359/64468792-5d712200-d0ee-11e9-9cb3-0122b26099b1.png)
For example: 
![image](https://user-images.githubusercontent.com/25836359/64468810-85608580-d0ee-11e9-9c7b-5d462527c4fa.png)
* Reference isn't connected to anything here. That limits us to a 2.5V internal VCC (which limits the maximum input voltage to 2.5V) and less precise than an external reference. It's ok, it's just better to use closer to the full scale of the ADC. 
* Address pins: Usually good to have 0Ohms DNPed to GND in addition to your connection to 5V. 
![image](https://user-images.githubusercontent.com/25836359/64468830-c6589a00-d0ee-11e9-97ae-f59d75efb5a9.png) right now with those zero ohm resistors you'd have a short from 5V directly to GND, which isn't great. 
* I tend to make all of my pins passive, rather than messing with the I/O designations. Probably not the best practice, but I haven't found too much of an advantage for doing that with designs of our size. 
* Decoupling: I'd probably mention to place close to the ADC input pins or something of that nature. It's a good reminder for the layout person to do that when they reference schematics to place components. 
![image](https://user-images.githubusercontent.com/25836359/64468889-5f87b080-d0ef-11e9-98cf-bd2958b38144.png)
* Where'd you get 7.5K as  I2C pull up resistor value? That's probably fine but a bit odd. 
*

**Comment by rcastle1** [comment]
Libraries: Let's use the manufacturer part search method. I'm not sure if that's included in the multivibrator tutorial or not, but you just search for your component in this panel, and then right click on your part, and IMPORT into your library either as a new component or you can just add links. This makes it super easy to generate a BOM at the end of the process, which is awesome. 
![image](https://user-images.githubusercontent.com/25836359/64468957-3156a080-d0f0-11e9-8b9c-159c172c546e.png)
    * One note on this, it will make the supplier part number visible by default, which I don't like. Hiding it is good practice. 
* Nice job updating the description and reference designator default. 
* make sure you link your component and your footprint here otherwise you will get import errors: 
![image](https://user-images.githubusercontent.com/25836359/64468984-b2159c80-d0f0-11e9-93a9-7c85311950df.png)
* More of a preference, but I usually go with rectangular pads rather than rounded. 
![image](https://user-images.githubusercontent.com/25836359/64469014-0d478f00-d0f1-11e9-906e-855b4545dd4e.png)
* I'm assuming you did the dimensions properly because I'm too lazy to check. Make sure your units agree! the IPC footprint wizard is really nice, right? 
* Another preference thing, but if you are in the wizard, select "Generate STEP Model Preview" to generate a decent render rather than a grey box. Can be helpful to see what your pin sizing is and what not. 
![image](https://user-images.githubusercontent.com/25836359/64469045-70392600-d0f1-11e9-85e3-d78b55605b95.png)

![image](https://user-images.githubusercontent.com/25836359/64469029-441da500-d0f1-11e9-9a53-7a5a2ae9062a.png)

**Comment by rcastle1** [comment]
One other thing that seems trivial, but can make a board un-usable: Your 5V and 3.3V rails are named POS5V, but the convention followed in the power.sch sheet use V-POS3V3. I know it barely seems like a difference, but Altium thinks those are two separate nets, so we are effectively not powering anything here, which would be a bummer.

**Comment by rcastle1** [comment]
Closing as resolved. 
![image](https://user-images.githubusercontent.com/25836359/64914077-adb13b00-d711-11e9-86cc-b9a08e2ae298.png)
