### ISSUE TITLE
F6257CT-ND Wrong footprint

### ISSUE THREAD

**Issue by dawiggleman** [badgerloop-software/hardware#16]
This footprint was too small last year, and I am not sure it got changed as this is just the 0805 resistor footprint. @rcastle1 Want me to create correct one and fix on my branch and push?

![image](https://user-images.githubusercontent.com/39936933/68148061-e810aa80-ff00-11e9-8bf3-c0ab3ac210e3.png)

**Comment by rcastle1** [comment]
@dawiggleman Sounds good.
