### ISSUE TITLE
Main IO Sch Initial Comments

### ISSUE THREAD

**Issue by rcastle1** [badgerloop-software/hardware#19]
I'm going through the main IO board schematics and recording thoughts here:

![image](https://user-images.githubusercontent.com/25836359/68999933-74ba5180-088d-11ea-81bc-df6fee337023.png)

* Specify the net that your GPIO is being connected to. Pod IV used generic net names because it routed out to the IO board connector, but here we should only have actual net names. (Note that EXTRA is a valid net name, for example, if you are routing out extra GPIO to a header or what not
* Add a No Connect directive to any unused pins. That makes it clear to a reviewer that you are aware that you don't want to actually use this pin, and it will eliminate no connect design rule checks later on. 

![image](https://user-images.githubusercontent.com/25836359/68999961-ef836c80-088d-11ea-8ef6-e76af57f4a1f.png)

* These are analog input pins, not address pins. Be careful with them though, as they have a maximum voltage of 1.8V IIRC and applying more than that can cause downstream failures
*  We'll need two UART interfaces broken out if possible, so that we can go one to each braking board. If there aren't enough, we'll need to let controls know asap because that will change the UART message schema. 
* Match net names to the correct values. For example, VOLT_SENSE is connected to the BB, but is that TELEM_V_BUS or TELEM__V_POS5V? 
* Should develop a pinout list that goes through all of the pins, what functions they are capable of (most pins will have alternative pins available) and what functions we are assigning them. 

![image](https://user-images.githubusercontent.com/25836359/69000023-d8914a00-088e-11ea-81f3-0304be5fc875.png)
* CAN TX is connected to UART RX, and vice versa. See https://www.thomas-wedemeyer.de/beaglebone-canbus-python.html

![image](https://user-images.githubusercontent.com/25836359/68999992-556ff400-088e-11ea-9d93-98b8b5347cfc.png)

* This will cause a lot of problems. It's on the I2C net. You should only use a pull-up resistor here

![image](https://user-images.githubusercontent.com/25836359/69000003-7a646700-088e-11ea-97b8-3aa82dd26119.png)

*  Delete unused components
* UART and I2C only need one header each. Don't need to have a GND

![image](https://user-images.githubusercontent.com/25836359/69000033-ff4f8080-088e-11ea-8dd0-9b1e01d147a7.png)
* This is a bit goofy. Consider editing for clarity and really think through the power on process and powering the boards independently for debug. 

![image](https://user-images.githubusercontent.com/25836359/69000044-43db1c00-088f-11ea-94d2-cd7ba4629e83.png)
* Bus filter calcs should be redone. We need to develop a power budget for the pod and resize components as necessary. 

![image](https://user-images.githubusercontent.com/25836359/69000050-5a817300-088f-11ea-911f-4e521b9ae0cc.png)

* Redo gain calcs, especially if you are going with the BB Analog input pins (which I advise against)

**Comment by dawiggleman** [comment]
Went through and checked sizing on inductors on filter, appears to be okay to stick with current ones with developed power budget. Replaced main fuse for an automotive fuse holder as that will be a higher current. 

Also did gain numbers for voltage telem and realized we need a 6.2k rather than a 16k. Changed for this schematic and will change on braking IO once libraries are merged and I make all changes to braking IO. 

Will need to add ADC for telem and other values rather than using beaglebone input pins. On my to-do
