### ISSUE TITLE
Prechage Board Review

### ISSUE THREAD

**Issue by rcastle1** [badgerloop-software/hardware#47]
**Mechanical**
![image](https://user-images.githubusercontent.com/25836359/76156719-45855580-60b3-11ea-94b1-aacdbeccb9c3.png)
* Be careful when screwing the board down. I'd pull the copper pour back a bit. That silkscreen should be the diameter of a 4-40 screwhead, but in case you change hardware, you'll want to avoid any copper underneath the screwhead in case you wear off the soldermask, especially for HV nets. Could lead to insulation problems even if it's not a hard short.  
![image](https://user-images.githubusercontent.com/25836359/76156676-8b8de980-60b2-11ea-9c14-8cf7492094e1.png)
* May be worth editing these long leads in the components. May be difficult to edit once its in NX and those will surely stick out of the enclosure. 

**Placement**
![image](https://user-images.githubusercontent.com/25836359/76156886-ae6dcd00-60b5-11ea-8fc7-989460ebab5d.png)
* Make your diodes have the same orientation. Easier to assemble, harder put them on backwards. 
![image](https://user-images.githubusercontent.com/25836359/76156924-67340c00-60b6-11ea-91ca-3df0fdfd8a79.png)
* Place I1 as close as you can to pin 0. (standard prefix for inductors is L, not I btw, thanks Heinrich Lenz. There are too may Is floating around in EE anyway) Rotate 180 degrees. Rotate C1 90 degrees and place it closer to U1
* TP5 will be inaccessible
![image](https://user-images.githubusercontent.com/25836359/76157103-4e792580-60b9-11ea-99b9-16da9bd06698.png)
* Rotate LED3 180 degrees. See how that makes the routing simpler? 

**Routing**
![image](https://user-images.githubusercontent.com/25836359/76156775-dd833f00-60b3-11ea-85f8-d7fb4987f8cb.png)
* Remember, your current will be the same on either side of this fuse. So having a huge pour on one side and a 10 mil trace on the other kinda negates having the huge pour (not exactly, as I^2*R losses are a function of length). 
![image](https://user-images.githubusercontent.com/25836359/76156835-bc6f1e00-60b4-11ea-8da4-9c4b12d20c8f.png)
* Avoid this 90 deg inside corner. In this case, I'd probably just pull combine the two 45 deg corners into a single, larger one though to avoid the mount hole.
* Also, it's nice if you have a standard size for your 45deg polygon pour corners. 
* Align the bottom of the IN and OUT copper polygons. 
* I'd make the input routes to U1 pours instead of 10mil traces. I don't expect you having issues as this DCDC converter is very integrated, but good practice for supplies. I didn't see a reference layout for this chip, but maybe look around for one. 
![image](https://user-images.githubusercontent.com/25836359/76156983-50da8000-60b7-11ea-949c-e5d08892fa61.png)
* Not a big deal on this board, as everything is basically DC, but.... this fanout is not the best. 
* TP2 will be inaccessible in that position. 
![image](https://user-images.githubusercontent.com/25836359/76156993-83847880-60b7-11ea-8d8f-6b5c2e15df93.png)
* Not sure what the point of doing this is if you're routing the rest of your avionics_RET net as 10 mil traces. Think of it just as your regular GND, try to maximize the ground plane, avoid splitting it up, and provide the shortest signal return path to reduce EMI.
* NetLED1_1 doesn't need to be a pour. 
* Reconsider your placement of this set of components. You can easily reduce your total trace length by flipping a few components 180 degrees. (Again, this board, not a big deal, but think of this as a board to practice good technique and to show off in interviews)
![image](https://user-images.githubusercontent.com/25836359/76157043-6a2ffc00-60b8-11ea-8c4e-057d678be5b3.png) ![image](https://user-images.githubusercontent.com/25836359/76157050-816ee980-60b8-11ea-98f2-cdcd66df41c9.png)
* Couple things about fanout-- you want to escape your "dense" part of the board with as little copper as possible. Come straight out, and get as much clearance between holes as possible. Notice how I moved the trace to come out directly at 45degrees and I moved the trace to be in the center of pins 6 and 7. Cheap fab houses can have huge tolerance on their drill hole centers. 
* In general, move your traces away from any holes, mount holes, connector holes, through holes, etc. 
![image](https://user-images.githubusercontent.com/25836359/76157090-1d98f080-60b9-11ea-8fef-b3f8015239ac.png)
* I see you're somewhat limited on space in this area, but having 3/4 LED connections be huge and 1 be 10 mil doesn't make much sense. 

**DRC**
![image](https://user-images.githubusercontent.com/25836359/76157125-926c2a80-60b9-11ea-9bee-05bc6233f5fb.png)
* Minimum solder mask sliver here. Double check footprint. 
* Add a 10 mil board outline clearance rule. getting 19 violations. 

**Misc**
Test points:
* While I'm generally against it, but you might consider switching your test points on this board to be more friendly to scope probes. Like https://www.digikey.com/product-detail/en/te-connectivity-amp-connectors/RCU-0C/A106145TR-ND/2366048 Avoid the ceramic through hole ones, as those can get charred easily by a heat gun and assembly through hole sucks generally. 
* Consider renaming TP* with the net name, or some shorter indicator. Makes it easier to probe/debug on the fly. 
* Change the board dimensions to your text layer. Depending on the site, you'll get nuisance object outside board outline warnings. 

**Silkscreen**
![image](https://user-images.githubusercontent.com/25836359/76156690-cb54d100-60b2-11ea-9dd6-e7228a5d0798.png)
* Purely cosmetic, but you could adjust the silkscreen on this footprint to line up with the contactor better.
* Add the revision number to the silkscreen. Could save some headache if you end up revving with only minor or internal changes
* Add a rectangle in silkscreen so you can label board serial number easily
* Could probably hide the Ref Des silkscreen for the mount holes :) 
* Badgerloop logo resolution is bad
* I'd line up the badgerloop, altium and board name silkscreen, maybe rotate 90 degrees. Looks odd having them separate. Definitely a function of board space though
* Add descriptive connector names. 
* Add descriptive LED functionality in the silkscreen. 
![image](https://user-images.githubusercontent.com/25836359/76157172-2d650480-60ba-11ea-92d9-7757f193a023.png)
* Maybe get rid of this. You'll get whatever the proto board shop wants. 
![image](https://user-images.githubusercontent.com/25836359/76157188-4ec5f080-60ba-11ea-8f97-fcbe1c64d463.png)

**Design for Manufacturing**
* Remove the duplicate columns, template, from this chart. 
* Add units to board dimensions. 
* Good practice to move your board origin to the bottom left corner of the board. 
* Add three fiducials to 3 corners, if you can. I'm sure you'll never get this board professionally assembled, but they're easy to add just in case. 
* What does the enclosure look like? Will those LEDs be visible when it's in the enclosure? What about a right angle LED that could slide into a pocket of the board? 

All I got for now! I didn't look at the schematics or footprints very closely, so be sure to double check those, as that's where you'll really run into the issues.

**Comment by dawiggleman** [comment]
Thanks for the review Ryan, all great points. Will be sure to look at all of these and implement
