### ISSUE TITLE
Main IO Review

### ISSUE THREAD

**Issue by rcastle1** [badgerloop-software/hardware#48]
Same general comments apply as Precharge review, so I won't repeat myself (too much) here. Check through that list as you work through issues presented here. Especially the housekeeping stuff. 
**3D Observations**
![image](https://user-images.githubusercontent.com/25836359/76277759-da6c8800-6246-11ea-9741-a5d0dd0a8d87.png)
* Adjust height of these components
* Add rev to silkscreen

**General**
* Repour your polygons and re-run DRC
* Add a 10 mil board outline clearance rule. 
![image](https://user-images.githubusercontent.com/25836359/76279316-6a143580-624b-11ea-8d70-7de796042ad6.png)
* I'm not a fan of this, but i guess it's whatever at this point. If you have the room allocated, you may as well just populate it with a basic I2C (to BB), retro and GPIO interface. If you end up needing it great, if not, don't popuate it. copper is cheap. But the way it is now you're just paying for the extra board space and forcing yourself to spin if there is a arduino requirement. 

**Power**
![image](https://user-images.githubusercontent.com/25836359/76279636-7c42a380-624c-11ea-96e3-68def893714b.png)
![image](https://user-images.githubusercontent.com/25836359/76279645-8795cf00-624c-11ea-837e-c1142213421d.png)
* you are very likely to get issues with this power supply. follow layout as close as possible. 
* How did you spec that inductor? That package seems large.
* You only have 1 electrolytic output cap. I'm very skeptical of the schematic. You probably want a 0.1uF and a few 1uF output caps. 22+4.7*2 doesn't seem like enough input cap either. 
* Where do you get compensation component values? 
![image](https://user-images.githubusercontent.com/25836359/76279756-0ee34280-624d-11ea-93bb-60f301885f3d.png)
* Adjust gain to use more of the ADC input range
* Power supplies are one of the few things that really matter for routing, placement, etc. 
* Similar comment for the other supply. Recommend just re-doing that portion of the board.
* i won't be online for bloop stuff for the next couple of weeks, apologies. 
* you might consider using your extra space on the board for a backup off the shelf power supply like we've used in the past. (just remember to only populate one or the other!)

**Routing**
* **REPOR POLYGONS** You have to repour your polygons. That means it'll update your pours to have clearance around traces, components, etc. When I run a DRC I get > 500 errors. 
![image](https://user-images.githubusercontent.com/25836359/76277919-71394480-6247-11ea-9c13-47a0613bc7c6.png)
* Clean up areas like this. Seeing them in a few places. Those small crevasses can cause acid traps long-term (although it depends on the quality of the fab house)
![image](https://user-images.githubusercontent.com/25836359/76278054-d7be6280-6247-11ea-83db-06e40f70bc87.png)
* Altium tip: Gloss routes can clean up stuff like this easily. Select route, tab to extend selection, then do <U> + <L> to gloss route. It'll smooth out any of the discontinuities.
* Could shorten some of these routes, but it's not a big deal
* CAN routing is not idea. CAN is a differential pair signal. You need to route signals close to each other to avoid signal integrity issues. Ideally you'd do length matching. Route CAN_H and CAN_L with the minimum trace distance between them as possible. Avoid stubs. Basically, just re-route high and low together. It's one of the only signals on the board that you might actually run into signal integrity / skew issues with. RXD/TXD side looks better, but could still be improved. 
![image](https://user-images.githubusercontent.com/25836359/76278567-1b659c00-6249-11ea-9ac5-8d46650b4034.png)
* Don't do this. Routing underneath a resistor isn't IPC Class 3, which is whatever for this board, (although generally you should avoid this). Except in this case, It's a really bad idea to route 2 high frequency, uncoupled signals underneath.
![image](https://user-images.githubusercontent.com/25836359/76278676-65e71880-6249-11ea-8b37-e91d8ae8aa5e.png)
* vias are too close together. via current capacity is variable, but you could probably just get away with 4 here (if you really need more than 1)
![image](https://user-images.githubusercontent.com/25836359/76278976-3d135300-624a-11ea-9c73-2efc4b0550ef.png)
![image](https://user-images.githubusercontent.com/25836359/76278993-4c929c00-624a-11ea-901d-f13a325adc9b.png)
* Change your plane connect type (not just these two locations)
![image](https://user-images.githubusercontent.com/25836359/76279086-aa26e880-624a-11ea-876d-2b8144ebbf66.png)
* Don't do this. come straight out from a pad. very likely to get a short if you do this. 
* Tight routing here. good job on placement
![image](https://user-images.githubusercontent.com/25836359/76279173-f7a35580-624a-11ea-9c50-8fb0a2c674f8.png)
* Not a great pour
![image](https://user-images.githubusercontent.com/25836359/76279225-1570ba80-624b-11ea-9e6b-ce8ff42c90fe.png)
* Generally, you want to keep I2C lines away from one another to avoid crosstalk (I2C1_SDA, I2C2_SDA, I2C1_SCL, I2C2_SCL, etc)

**Silkscreen**
* A lot of silk to soldermask, silk to silk, and soldermask silver errors. 
* Move board name and such so that you can see it with the beaglebone populated
* Same comments as before

** Overall**
* Good work on the board. Probably the most complicated board you've done, so that's fun. can definitely be a little frustrating if you think you're set to go and then have to go back, but that's what PCB design is all about haha. 
* Definitely work on schematic review, double check footprints, and improve any high speed and power supplies.

**Comment by keving98g** [comment]
Thanks for the feedback Ryan! This is very helpful not only for this board but PCB design in general.
