### ISSUE TITLE
CAN Transceiver- TX/RX Swapped

### ISSUE THREAD

**Issue by dawiggleman** [badgerloop-software/hardware#72]
![image](https://user-images.githubusercontent.com/39936933/115129406-31e13980-9fab-11eb-8be7-c2ea5721b6bc.png)
On datasheet for CAN Transceiver SN65HVD256, the TX needs to go to the beaglebone TX pin, and RX to RX. I flipped these on MainIO, currently fixed with deadbug right now.

Incorrect configuration on hardware:
![image](https://user-images.githubusercontent.com/39936933/115129436-6ead3080-9fab-11eb-92e8-b2eb4eaba62f.png)

**Comment by keving98g** [comment]
The current schematic is correct. Pin 24 on the Beaglebone is a multi-purpose pin for _uart1_txd | mmc2_sdwp | dcan1_rx | I2C1_SCL_ so it is the CAN1_RXD signal. The deadbug has been reverted so the hardware is matching the current design and is verified.
